spring.application.name=springai
server.servlet.context-path=/springai

# disable specific OpenAI auto-configs we don't use
spring.ai.openai.api-key=your_api_key
spring.ai.openai.chat.model=gpt-4o-mini
#spring.ai.model.embedding=openai
spring.ai.openai.embedding.model=text-embedding-3-small

#***************************
#APPLICATION FAILED TO START
#***************************
#
#Description:
#
#The bean 'vectorStore', defined in class path resource [org/springframework/ai/vectorstore/milvus/autoconfigure/MilvusVectorStoreAutoConfiguration.class], could not be registered. A bean with that name has already been defined in sk.mkrajcovic.springai.SpringaiApplication and overriding is disabled.
#
#Action:
#
#Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
#spring.main.allow-bean-definition-overriding=true #no longer needed
spring.ai.model.audio.speech=none
spring.ai.model.audio.transcription=none
spring.ai.model.image=none
spring.ai.model.moderation=none
